import{useEffect,useRef,useState}from'react';import{Routes,Route,useNavigate,NavLink,useLocation}from'react-router-dom';import{MapContainer,Marker,Popup,TileLayer,useMap}from'react-leaflet';import L from'leaflet';import{AlertTriangle,ArrowRight,Building2,Check,ChevronRight,Clock,Compass,ExternalLink,Heart,Home,Languages,List,LocateFixed,Map,MapPin,Menu as MenuIcon,Navigation,Phone,Search,Send,Share2,ShieldCheck,Siren,Star,Wrench}from'lucide-react';
import{categories,keywordMap,provinces,services}from'./data';import{districtsFor}from'./turkeyDistricts';import{getCurrentLocation,LocationError}from'./location';import{findPlaces,track}from'./api';import{getInitialLang,t}from'./i18n';import type{Lang,Place,Position}from'./types';

const marker=L.divIcon({className:'place-marker',html:'<span></span>',iconSize:[28,36],iconAnchor:[14,36]});
function Layout({children,lang,setLang}:{children:React.ReactNode;lang:Lang;setLang:(l:Lang)=>void}){return <div dir={lang==='ar'?'rtl':'ltr'}><header className="topbar"><NavLink to="/" className="brand"><span className="brand-pin"><MapPin/></span><span>YANIMDA <b>TÜRKİYE</b></span></NavLink><label className="lang"><Languages/><select value={lang} onChange={e=>setLang(e.target.value as Lang)} aria-label="Dil"><option value="tr">TR</option><option value="en">EN</option><option value="de">DE</option><option value="ru">RU</option><option value="ar">AR</option><option value="fr">FR</option></select></label></header>{children}<nav className="bottom-nav"><NavLink to="/"><Home/><span>{t(lang,'home')}</span></NavLink><NavLink to="/nearby"><Compass/><span>{t(lang,'nearby')}</span></NavLink><NavLink to="/services"><Wrench/><span>{t(lang,'services')}</span></NavLink><NavLink to="/emergency" className="emergency-tab"><Siren/><span>{t(lang,'emergency')}</span></NavLink><NavLink to="/menu"><MenuIcon/><span>{t(lang,'menu')}</span></NavLink></nav></div>}

function HomePage({lang}:{lang:Lang}){
  const nav=useNavigate();
  const[q,setQ]=useState('');
  const[locOpen,setLocOpen]=useState(false);
  const[province,setProvince]=useState('');
  const[district,setDistrict]=useState('');
  const[locating,setLocating]=useState(false);
  const[locationError,setLocationError]=useState('');
  const districtOptions=districtsFor(province);
  const go=(category:string,pos?:Position,manualProvince=province,manualDistrict=district)=>
    nav('/nearby',{state:{category,position:pos,province:manualProvince,district:manualDistrict}});
  const search=()=>{
    const normalized=q.toLocaleLowerCase('tr').trim();
    const key=Object.keys(keywordMap).find(k=>normalized.includes(k));
    go(key?keywordMap[key]:(normalized||'service'));
    track('search',{query:normalized,category:key?keywordMap[key]:'service'});
  };
  const locationMessage=(error:unknown)=>{
    if(error instanceof LocationError){
      if(error.code==='permission_denied')return 'Konum izni verilmedi. Tarayıcı ayarlarından konum iznini açıp tekrar deneyin.';
      if(error.code==='timeout')return 'Konum bulunamadı. Lütfen açık bir alanda tekrar deneyin.';
      if(error.code==='unsupported')return 'Bu cihazda konum özelliği desteklenmiyor. İl ve ilçe seçerek devam edebilirsiniz.';
    }
    return 'Konumunuz alınamadı. İl ve ilçe seçerek devam edebilirsiniz.';
  };
  const locate=async()=>{
    if(locating)return;
    setLocating(true);setLocationError('');setLocOpen(false);
    try{
      const pos=await getCurrentLocation();
      track('location_click',{lat:pos.lat,lon:pos.lon});
      go('service',pos,'','');
    }catch(error){
      setLocationError(locationMessage(error));
      setLocOpen(true);
    }finally{setLocating(false)}
  };
  return <main><section className="hero"><div className="hero-copy"><span className="eyebrow"><ShieldCheck/> {t(lang,'allTurkey')}</span><h1>Yakınındaki çözüm,<br/><em>şimdi yanında.</em></h1><p>{t(lang,'tagline')}</p><div className="searchbox"><Search/><input value={q} onChange={e=>setQ(e.target.value)} onKeyDown={e=>e.key==='Enter'&&search()} placeholder={t(lang,'search')} aria-label={t(lang,'search')}/><button onClick={search} aria-label={t(lang,'searchButton')}><ArrowRight/></button></div><div className="location-actions"><button className="primary" onClick={locate} disabled={locating}>{locating?<><span className="spinner"/>Konum bulunuyor...</>:<><LocateFixed/>{t(lang,'useLocation')}</>}</button><button className="ghost" onClick={()=>{setLocationError('');setLocOpen(!locOpen)}}><MapPin/>{t(lang,'chooseLocation')}</button></div>{locationError&&<div className="location-error" role="alert">{locationError}</div>}{locOpen&&<div className="location-panel"><select value={province} onChange={e=>{setProvince(e.target.value);setDistrict('')}}><option value="">{t(lang,'selectProvince')}</option>{provinces.map(p=><option key={p} value={p}>{p}</option>)}</select><select value={district} onChange={e=>setDistrict(e.target.value)} disabled={!province}><option value="">{province?'İlçe seçin':'Önce il seçin'}</option>{districtOptions.map(d=><option key={d} value={d}>{d}</option>)}</select><button disabled={!province||!district} onClick={()=>go('service',undefined,province,district)}>{t(lang,'searchButton')}<ChevronRight/></button><small>{t(lang,'locationHint')}</small></div>}</div><div className="hero-orbit" aria-hidden="true"><div className="orbit-map"><span className="pulse"></span><MapPin/></div><span className="orbit-label one">81 il</span><span className="orbit-label two">Açık veri</span><span className="orbit-label three">Ücretsiz</span></div></section><section className="category-section"><div className="section-title"><div><span className="kicker">HIZLI ERİŞİM</span><h2>Şu an neye ihtiyacın var?</h2></div><NavLink to="/nearby">Tümünü gör <ArrowRight/></NavLink></div><div className="category-grid">{categories.map((c,i)=><button key={c.id} className={`category-card ${c.color}`} style={{'--delay':`${i*35}ms`} as React.CSSProperties} onClick={()=>c.id==='emergency'?nav('/emergency'):c.id==='service'?nav('/services'):go(c.id)}><span><c.icon/></span><b>{c.label}</b><ChevronRight/></button>)}</div></section><section className="trust-strip"><ShieldCheck/><div><b>Doğrulanabilir kaynaklar</b><p>Sonuçlar OpenStreetMap ve onaylanmış başvurulardan gelir. Kayıt uydurulmaz.</p></div></section></main>
}
function Recenter({position}:{position:Position}){const map=useMap();useEffect(()=>{map.setView([position.lat,position.lon],14)},[map,position]);return null}
function PlaceCard({place,lang}:{place:Place;lang:Lang}){const[fav,setFav]=useState(()=>JSON.parse(localStorage.getItem('favorites')||'[]').some((p:Place)=>p.id===place.id));const[reported,setReported]=useState(false);const toggle=()=>{const all:Place[]=JSON.parse(localStorage.getItem('favorites')||'[]');const next=fav?all.filter(p=>p.id!==place.id):[...all,place];localStorage.setItem('favorites',JSON.stringify(next));setFav(!fav);track('favorite_click',{category:place.category})};const dir=`https://www.google.com/maps/dir/?api=1&destination=${place.lat},${place.lon}`;const report=async()=>{const reason=window.prompt('Sorun kodu: wrong_info, wrong_phone, wrong_address veya closed');if(!reason)return;const r=await fetch('/api/reports',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({placeId:place.id,placeName:place.name,reason})});if(r.ok)setReported(true)};return <article className="place-card"><div className="place-top"><div className="place-icon"><MapPin/></div><div><h3>{place.name}</h3><p>{place.address||'Adres bilgisi kaynakta yer almıyor.'}</p></div><button className={`heart ${fav?'selected':''}`} onClick={toggle} aria-label={t(lang,'favorite')}><Heart/></button></div><div className="place-meta">{place.distance!==undefined&&<span><Navigation/>{place.distance<1?`${Math.round(place.distance*1000)} m`:`${place.distance.toFixed(1)} km`} {t(lang,'distance')}</span>}{place.openingHours&&<span><Clock/>{place.openingHours}</span>}<span className="source"><ShieldCheck/>{t(lang,'source')}: {place.source}</span></div><div className="place-actions">{place.phone&&<a href={`tel:${place.phone}`} onClick={()=>track('phone_click',{category:place.category})}><Phone/>{t(lang,'call')}</a>}{place.whatsapp&&<a href={`https://wa.me/${place.whatsapp.replace(/\D/g,'')}`} target="_blank" rel="noreferrer" onClick={()=>track('whatsapp_click',{category:place.category})}><Send/>WhatsApp</a>}<a href={dir} target="_blank" rel="noreferrer" onClick={()=>track('directions_click',{category:place.category})}><Navigation/>{t(lang,'directions')}</a><button onClick={()=>navigator.share?.({title:place.name,text:place.address||place.name,url:dir})}><Share2/>Paylaş</button><button onClick={report} disabled={reported}><AlertTriangle/>{reported?'Bildirildi':'Hata bildir'}</button></div></article>}
function NearbyPage({lang}:{lang:Lang}){
  const nav=useNavigate();
  const routerLocation=useLocation();
  const state=(routerLocation.state||{}) as {category?:string;position?:Position;province?:string;district?:string};
  const[category,setCategory]=useState(state.category||'pharmacy');
  const[position,setPosition]=useState<Position|undefined>(state.position);
  const[province,setProvince]=useState(state.province||'');
  const[district,setDistrict]=useState(state.district||'');
  const[places,setPlaces]=useState<Place[]>([]);
  const[loading,setLoading]=useState(false);
  const[locating,setLocating]=useState(false);
  const[error,setError]=useState('');
  const[view,setView]=useState<'list'|'map'>('list');
  const districtOptions=districtsFor(province);
  const requestId=useRef(0);

  useEffect(()=>{
    if(state.category!==undefined)setCategory(state.category);
    if(state.position!==undefined)setPosition(state.position);
    if(state.province!==undefined)setProvince(state.province);
    if(state.district!==undefined)setDistrict(state.district);
  },[state.category,state.position?.lat,state.position?.lon,state.province,state.district]);

  const load=async()=>{
    if(!position&&!(province&&district))return;
    const id=++requestId.current;
    setLoading(true);setError('');
    try{
      const result=await findPlaces(category,position,province,district);
      if(id===requestId.current)setPlaces(result);
    }catch{
      if(id===requestId.current)setError(category==='pharmacy'?'Nöbetçi eczane bilgisi şu anda alınamıyor.':t(lang,'noResults'));
    }finally{if(id===requestId.current)setLoading(false)}
  };
  useEffect(()=>{void load()},[category,position?.lat,position?.lon,province,district]);

  const locationMessage=(e:unknown)=>e instanceof LocationError&&e.code==='permission_denied'
    ?'Konum izni verilmedi. Tarayıcı/telefon ayarlarından konum iznini açıp tekrar deneyin.'
    :'Konumunuz alınamadı. İl ve ilçe seçerek devam edebilirsiniz.';
  const locate=async()=>{
    if(locating)return;
    setLocating(true);setError('');
    try{
      const pos=await getCurrentLocation();
      setPosition(pos);setProvince('');setDistrict('');
      track('location_click',{lat:pos.lat,lon:pos.lon});
    }catch(e){setError(locationMessage(e))}finally{setLocating(false)}
  };
  const center=position||places[0]&&{lat:places[0].lat,lon:places[0].lon};
  const manualSearch=async()=>{if(!province||!district)return;setPosition(undefined);setLoading(true);setError('');try{setPlaces(await findPlaces(category,undefined,province,district))}catch{setError(category==='pharmacy'?'Nöbetçi eczane bilgisi şu anda alınamıyor.':t(lang,'noResults'))}finally{setLoading(false)}};
  return <main className="inner"><div className="page-head"><button className="back" onClick={()=>nav(-1)}>‹</button><div><span className="kicker">CANLI AÇIK VERİ</span><h1>{t(lang,'nearby')}</h1></div><button className="locate-round" onClick={locate} disabled={locating} aria-label="Konumumu kullan">{locating?<span className="spinner dark"/>:<LocateFixed/>}</button></div><div className="filter-row"><select value={category} onChange={e=>setCategory(e.target.value)}>{categories.filter(c=>!['emergency','service'].includes(c.id)).map(c=><option value={c.id} key={c.id}>{c.label}</option>)}{services.map(s=><option value={s[0]} key={s[0]}>{s[1]}</option>)}</select><select value={province} onChange={e=>{setProvince(e.target.value);setDistrict('');setPosition(undefined)}}><option value="">{t(lang,'selectProvince')}</option>{provinces.map(p=><option key={p} value={p}>{p}</option>)}</select><select value={district} onChange={e=>{setDistrict(e.target.value);setPosition(undefined)}} disabled={!province}><option value="">{province?'İlçe seçin':'Önce il seçin'}</option>{districtOptions.map(d=><option key={d} value={d}>{d}</option>)}</select><button onClick={manualSearch} disabled={!province||!district}><Search/></button></div>{error&&<div className="location-error inner-error" role="alert">{error}</div>}<div className="results-toolbar"><h2>{t(lang,'results')} <span>{places.length}</span></h2><div><button className={view==='list'?'active':''} onClick={()=>setView('list')}><List/>{t(lang,'list')}</button><button className={view==='map'?'active':''} onClick={()=>setView('map')}><Map/>{t(lang,'map')}</button></div></div>{loading?<div className="skeletons">{[1,2,3].map(i=><div key={i} className="skeleton"/>)}</div>:!position&&!province?<Empty text={t(lang,'locationHint')} action={locate}/>:!position&&!district?<Empty text="İlçe seçerek arama yapın veya Konumumu Kullan butonuna basın."/>:places.length===0?<Empty text={t(lang,'noResults')}/>:view==='list'?<div className="places-list">{places.map(p=><PlaceCard key={p.id} place={p} lang={lang}/>)}</div>:center&&<div className="map-wrap"><MapContainer center={[center.lat,center.lon]} zoom={13} scrollWheelZoom><TileLayer attribution='&copy; OpenStreetMap contributors' url="https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png"/><Recenter position={center}/>{position&&<Marker position={[position.lat,position.lon]} icon={marker}><Popup>Konumunuz</Popup></Marker>}{places.map(p=><Marker key={p.id} position={[p.lat,p.lon]} icon={marker}><Popup><b>{p.name}</b><br/>{p.address}</Popup></Marker>)}</MapContainer></div>}</main>
}
function Empty({text,action}:{text:string;action?:()=>void}){return <div className="empty"><div><MapPin/></div><h3>{text}</h3>{action&&<button className="primary" onClick={action}><LocateFixed/>Konumumu Kullan</button>}</div>}

function ServicesPage(){const nav=useNavigate();return <main className="inner"><div className="page-head"><button className="back" onClick={()=>nav(-1)}>‹</button><div><span className="kicker">USTA VE HİZMETLER</span><h1>Çözüm Merkezi</h1></div></div><p className="lead">İhtiyacını seç; yakındaki gerçek işletmeleri açık verilerden bul.</p><div className="service-grid">{services.map(([id,label,Icon])=><button key={id} onClick={()=>nav('/nearby',{state:{category:id}})}><span><Icon/></span><b>{label}</b><ChevronRight/></button>)}</div><button className="add-banner" onClick={()=>nav('/add-business')}><Building2/><span><b>İşletmeni / Hizmetini Ekle</b><small>Ücretsiz başvur, inceleme sonrası yayınlansın</small></span><ArrowRight/></button></main>}
function EmergencyPage(){const calls=[['112','Acil Çağrı Merkezi','ambulance'],['112','Polis','police'],['112','İtfaiye','fire'],['112','Jandarma','gendarme']];return <main className="emergency-page"><div className="emergency-head"><Siren/><span>ACİL DURUM</span><h1>Yardıma tek dokunuşla ulaş.</h1><p>Türkiye’de tüm acil çağrılar 112’de birleşir.</p></div><a className="call-112" href="tel:112" onClick={()=>track('emergency_click',{service:'112'})}><span>112</span><b>HEMEN ARA</b><Phone/></a><div className="emergency-list">{calls.slice(1).map(([number,name,type])=><a href={`tel:${number}`} key={type} onClick={()=>track('emergency_click',{service:type})}><ShieldCheck/><span><b>{name}</b><small>Acil Çağrı Merkezi</small></span><Phone/></a>)}</div><div className="emergency-note"><AlertTriangle/> Yalnızca gerçek acil durumlarda arayın. Konumunuzu ve durumu kısa, net anlatın.</div></main>}

function AddBusinessPage(){
  const nav=useNavigate();
  const[status,setStatus]=useState('');
  const[province,setProvince]=useState('');
  const[district,setDistrict]=useState('');
  const submit=async(e:React.FormEvent<HTMLFormElement>)=>{e.preventDefault();const form=e.currentTarget;const data=Object.fromEntries(new FormData(form));const r=await fetch('/api/submissions',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(data)});if(r.ok){setStatus('Başvurunuz alındı. Admin onayından sonra yayınlanacaktır.');form.reset();setProvince('');setDistrict('')}else setStatus('Başvuru gönderilemedi. Alanları kontrol edip tekrar deneyin.')};
  return <main className="inner form-page"><div className="page-head"><button className="back" onClick={()=>nav(-1)}>‹</button><div><span className="kicker">ÜCRETSİZ BAŞVURU</span><h1>İşletmeni / Hizmetini Ekle</h1></div></div><form onSubmit={submit}><label>İşletme adı<input name="name" required minLength={2}/></label><label>Kategori<select name="category" required>{services.map(s=><option value={s[0]} key={s[0]}>{s[1]}</option>)}</select></label><div className="two"><label>Telefon<input name="phone" type="tel" required pattern="[0-9+ ()-]{10,20}"/></label><label>WhatsApp<input name="whatsapp" type="tel" pattern="[0-9+ ()-]{10,20}"/></label></div><label>Adres<textarea name="address" required minLength={10}/></label><div className="two"><label>İl<select name="province" required value={province} onChange={e=>{setProvince(e.target.value);setDistrict('')}}><option value="">Seçin</option>{provinces.map(p=><option key={p} value={p}>{p}</option>)}</select></label><label>İlçe<select name="district" required value={district} onChange={e=>setDistrict(e.target.value)} disabled={!province}><option value="">{province?'İlçe seçin':'Önce il seçin'}</option>{districtsFor(province).map(d=><option key={d} value={d}>{d}</option>)}</select></label></div><label>Açıklama<textarea name="description" maxLength={800}/></label><label>Çalışma saatleri<input name="hours" placeholder="Örn. Pzt-Cmt 09:00-18:00"/></label><label className="consent"><input type="checkbox" required/> Bilgilerin başvuru değerlendirmesi amacıyla işlenmesini kabul ediyorum.</label><button className="primary submit" type="submit"><Send/>Başvuruyu Gönder</button>{status&&<p className="form-status"><Check/>{status}</p>}</form></main>
}
function MenuPage(){const nav=useNavigate();const favs:Place[]=JSON.parse(localStorage.getItem('favorites')||'[]');return <main className="inner"><div className="page-head"><div><span className="kicker">YANIMDA TÜRKİYE</span><h1>Menü</h1></div></div><div className="menu-list"><button onClick={()=>nav('/add-business')}><Building2/><span>İşletmeni / Hizmetini Ekle</span><ChevronRight/></button><button onClick={()=>nav('/favorites')}><Star/><span>Favoriler ({favs.length})</span><ChevronRight/></button><button onClick={()=>navigator.share?.({title:'Yanımda Türkiye',text:'İhtiyacın olanı, sana en yakın yerde bul.',url:location.origin})}><Share2/><span>Uygulamayı Paylaş</span><ChevronRight/></button><button onClick={()=>nav('/legal/privacy')}><ShieldCheck/><span>Gizlilik ve Yasal Metinler</span><ChevronRight/></button><button onClick={()=>nav('/admin')}><Building2/><span>Admin Girişi</span><ChevronRight/></button></div></main>}
function Favorites({lang}:{lang:Lang}){const nav=useNavigate();const[favs]=useState<Place[]>(()=>JSON.parse(localStorage.getItem('favorites')||'[]'));return <main className="inner"><div className="page-head"><button className="back" onClick={()=>nav(-1)}>‹</button><h1>Favoriler</h1></div>{favs.length?<div className="places-list">{favs.map(p=><PlaceCard key={p.id} place={p} lang={lang}/>)}</div>:<Empty text="Henüz favori eklemediniz."/>}</main>}
function Legal(){return <main className="inner legal"><span className="kicker">ŞEFFAFLIK</span><h1>Gizlilik ve yasal bilgiler</h1><nav><a href="#privacy">Gizlilik</a><a href="#kvkk">KVKK</a><a href="#cookies">Çerezler</a><a href="#terms">Kullanım</a></nav><section id="privacy"><h2>Gizlilik Politikası</h2><p>Yanımda Türkiye, yakın yerleri göstermek için konumunuzu yalnızca cihazınızda ve ilgili sorgu sırasında işler. Konum geçmişi oluşturmaz. Hizmet başvuruları inceleme amacıyla güvenli veritabanında saklanır.</p></section><section id="kvkk"><h2>KVKK Aydınlatması</h2><p>Başvuruyla paylaşılan işletme ve iletişim bilgileri, kaydı doğrulamak ve yayınlamak amacıyla işlenir. Düzeltme veya silme talepleri uygulama yöneticisine iletilebilir. Gereksiz özel nitelikli kişisel veri toplanmaz.</p></section><section id="cookies"><h2>Çerez Politikası</h2><p>Zorunlu oturum ve tercih depolaması dışında reklam veya takip çerezi kullanılmaz. Dil ve favoriler cihazınızda tutulur.</p></section><section id="terms"><h2>Kullanım Koşulları</h2><p>Açık veri kaynakları değişebilir. Acil durumda harita sonucuna güvenmek yerine 112 aranmalıdır. İşletme bilgileri yayınlanmadan önce incelenir; yanlış kayıtlar bildirildiğinde kaldırılır.</p></section></main>}
function Admin(){const[email,setEmail]=useState('');const[password,setPassword]=useState('');const[user,setUser]=useState<unknown>(null);const[error,setError]=useState('');const[data,setData]=useState<Record<string,unknown>|null>(null);useEffect(()=>{import('@netlify/identity').then(async m=>{const u=await m.getUser();setUser(u);if(u)fetch('/api/admin').then(r=>r.ok?r.json():Promise.reject()).then(setData).catch(()=>setError('Bu hesap admin yetkisine sahip değil.'))})},[]);const login=async(e:React.FormEvent)=>{e.preventDefault();try{const m=await import('@netlify/identity');const u=await m.login(email,password);setUser(u);location.reload()}catch{setError('Giriş başarısız. Bilgilerinizi kontrol edin.')}};if(!user)return <main className="admin-login"><div><ShieldCheck/><h1>Admin girişi</h1><p>Yetkili hesabınızla güvenli giriş yapın.</p><form onSubmit={login}><input type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="E-posta" required/><input type="password" value={password} onChange={e=>setPassword(e.target.value)} placeholder="Şifre" required/><button className="primary">Giriş Yap</button>{error&&<p>{error}</p>}</form></div></main>;const stats=(data?.stats||{}) as Record<string,number>;return <main className="admin"><aside><b>YT / ADMIN</b>{['Genel Bakış','Hizmetler','Hizmet Verenler','Eczaneler','Hastaneler','ATM','Başvurular','İstatistikler','Ayarlar'].map(x=><button key={x}>{x}</button>)}</aside><section><span className="kicker">GERÇEK ZAMANLI</span><h1>Genel Bakış</h1>{error?<Empty text={error}/>:!data?<div className="skeleton"/>:<><div className="stat-grid">{Object.entries({'Bugünkü ziyaretçi':'visitorsToday','Toplam ziyaretçi':'visitorsTotal','Bugünkü arama':'searchesToday','Toplam arama':'searchesTotal','Telefon tıklaması':'phoneClicks','Yol tarifi tıklaması':'directionsClicks','Acil tıklaması':'emergencyClicks','Favori sayısı':'favoriteClicks'}).map(([label,key])=><article key={key}><small>{label}</small><strong>{stats[key]||0}</strong></article>)}</div><div className="admin-panel"><h2>Son başvurular</h2>{((data.submissions||[]) as Array<Record<string,string>>).length?((data.submissions||[]) as Array<Record<string,string>>).map(s=><div className="application" key={s.id}><b>{s.name}</b><span>{s.category} · {s.province}/{s.district}</span><em>{s.status}</em></div>):<p>Henüz veri yok.</p>}</div></>}</section></main>}

export default function App(){const[lang,setLangState]=useState<Lang>(getInitialLang);const setLang=(l:Lang)=>{setLangState(l);localStorage.setItem('lang',l);document.documentElement.lang=l.toLowerCase()};useEffect(()=>{track('page_view',{path:location.pathname});let remove:undefined|(()=>void);import('@capacitor/app').then(async({App})=>{const h=await App.addListener('backButton',({canGoBack})=>{if(location.pathname!=='/'&&canGoBack)history.back();else if(location.pathname!=='/')location.href='/';else App.exitApp()});remove=()=>h.remove()}).catch(()=>undefined);return()=>remove?.()},[]);return <Layout lang={lang} setLang={setLang}><Routes><Route path="/" element={<HomePage lang={lang}/>}/><Route path="/nearby" element={<NearbyPage lang={lang}/>}/><Route path="/services" element={<ServicesPage/>}/><Route path="/emergency" element={<EmergencyPage/>}/><Route path="/add-business" element={<AddBusinessPage/>}/><Route path="/menu" element={<MenuPage/>}/><Route path="/favorites" element={<Favorites lang={lang}/>}/><Route path="/legal/:page" element={<Legal/>}/><Route path="/admin/*" element={<Admin/>}/><Route path="*" element={<main className="inner"><Empty text="Bu sayfa bulunamadı."/><NavLink to="/" className="primary">Ana sayfaya dön</NavLink></main>}/></Routes></Layout>}
