import {useEffect,useState} from 'react';
import type {FormEvent} from 'react';
import {NavLink,useLocation,useNavigate,useSearchParams,Routes,Route} from 'react-router-dom';
import {Activity,AlertTriangle,ArrowRight,Banknote,Bell,Building2,Bus,ChevronRight,Compass,Fuel,Heart,Hospital,Landmark,List,LocateFixed,LockKeyhole,Map as MapIcon,MapPin,Menu,Navigation,Phone,Search,ShieldCheck,Siren,Store,Stethoscope,UserCircle,Wrench} from 'lucide-react';
import type {LucideIcon} from 'lucide-react';
import {MapContainer,Marker,Popup,TileLayer} from 'react-leaflet';
import L from 'leaflet';
import {categories,provinces,services} from './data';
import {districtsFor} from './turkeyDistricts';
import {findPlaces} from './api';
import {getCurrentLocation,LocationError} from './location';
import type {Place,Position} from './types';

const marker=L.divIcon({className:'yt-marker',html:'<span></span>',iconSize:[30,38],iconAnchor:[15,38]});
const imgs={
hero:'https://images.unsplash.com/photo-1524231757912-21f4fe3a7200?auto=format&fit=crop&w=1500&q=85',
pharmacy:'https://images.unsplash.com/photo-1585435557343-3b092031a831?auto=format&fit=crop&w=700&q=80',
hospital:'https://images.unsplash.com/photo-1586773860418-d37222d8fce3?auto=format&fit=crop&w=700&q=80',
fuel:'https://images.unsplash.com/photo-1542282088-fe8426682b8f?auto=format&fit=crop&w=700&q=80',
market:'https://images.unsplash.com/photo-1604719312566-8912e9227c6a?auto=format&fit=crop&w=700&q=80',
bakery:'https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&w=700&q=80',
transport:'https://images.unsplash.com/photo-1544620347-c4fd4a3d5957?auto=format&fit=crop&w=700&q=80',
burger:'https://images.unsplash.com/photo-1571091718767-18b5b1457add?auto=format&fit=crop&w=1500&q=80',
trend:'https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=1500&q=80'
};
const demo:Place[]=[
{id:'d1',name:'İstiklal Nöbetçi Eczanesi',category:'pharmacy',lat:41.035,lon:28.978,address:'İstiklal Caddesi No:123, Beyoğlu',phone:'+902122345678',source:'Yanında Türkiye',distance:.3,isDuty:true,openingHours:'7/24 Açık'},
{id:'d2',name:'Taksim Eczanesi',category:'pharmacy',lat:41.037,lon:28.985,address:'Taksim, Talimhane Cd.',phone:'+902122345679',source:'Yanında Türkiye',distance:.7,isDuty:true,openingHours:'7/24 Açık'},
{id:'d3',name:'Galata Eczanesi',category:'pharmacy',lat:41.025,lon:28.974,address:'Şahkulu, Beyoğlu',phone:'+902122345680',source:'Yanında Türkiye',distance:1.1,isDuty:true,openingHours:'7/24 Açık'},
{id:'d4',name:'Şişhane Eczanesi',category:'pharmacy',lat:41.028,lon:28.971,address:'Şişhane, Beyoğlu',phone:'+902122345681',source:'Yanında Türkiye',distance:1.4,isDuty:true,openingHours:'7/24 Açık'}
];

function Header(){
 const nav=useNavigate(); const[q,setQ]=useState('');
 return <header className="yt-header"><div className="yt-head"><NavLink to="/" className="yt-logo"><span><MapPin fill="currentColor"/></span><b>YANINDA <i>TÜRKİYE</i></b></NavLink><form className="yt-search" onSubmit={e=>{e.preventDefault();nav('/nearby',{state:{query:q}})}}><Search/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Ne arıyorsunuz? (Eczane, ATM, Hastane...)"/><span><MapPin/> İstanbul, Beyoğlu</span><button>Ara</button></form><div className="yt-actions"><button>☀</button><NavLink to="/admin">Giriş Yap</NavLink><button onClick={()=>nav('/menu')}><Menu/></button></div></div><nav className="yt-nav"><NavLink to="/">⌂ Ana Sayfa</NavLink><NavLink to="/nearby"><Compass/>Yakınımda</NavLink><NavLink to="/nearby"><MapIcon/>Harita</NavLink><NavLink className="danger" to="/emergency"><Siren/>Acil</NavLink><NavLink to="/favorites"><Heart/>Favoriler</NavLink><NavLink to="/news"><Landmark/>Haberler</NavLink><NavLink to="/contact"><Phone/>İletişim</NavLink></nav></header>
}

function MobileNav(){return <nav className="mobile-nav"><NavLink to="/">⌂<small>Ana Sayfa</small></NavLink><NavLink to="/nearby"><Compass/><small>Yakınımda</small></NavLink><NavLink to="/nearby"><MapIcon/><small>Harita</small></NavLink><NavLink to="/emergency"><Siren/><small>Acil</small></NavLink><NavLink to="/menu"><Menu/><small>Menü</small></NavLink></nav>}

function Ad({kind}:{kind:'top'|'mid'|'bottom'}){
 const d=kind==='top'?{img:imgs.pharmacy,title:'GÜVEN ECZANESİ',text:'7/24 HİZMETİNİZDE',button:'Hemen Konumunu Al',cls:'red'}:kind==='mid'?{img:imgs.burger,title:'BURGER KING',text:'LEZZET HER ZAMAN YANINDA',button:'En Yakın Şubeyi Bul',cls:'burger'}:{img:imgs.trend,title:'trendyol',text:'ARADIĞIN HER ŞEY TRENDYOL’DA',button:'Hemen İncele',cls:'trend'};
 return <a href="#" className={'yt-ad '+d.cls} onClick={e=>e.preventDefault()}><img src={d.img} alt=""/><div><small>REKLAM</small><strong>{d.title}</strong><b>{d.text}</b><button>{d.button}</button></div></a>
}

const quick:[string,string,LucideIcon,string][]=[
['pharmacy','Nöbetçi Eczane',Stethoscope,'red'],['hospital','Hastane',Hospital,'blue'],['emergency','Acil Servis',Siren,'red'],['atm',"ATM'ler",Banknote,'purple'],['fuel','Akaryakıt',Fuel,'green'],['market','Market',Store,'orange'],['restaurant','Fırın',Store,'amber'],['taxi','Ulaşım',Bus,'blue'],['police','Polis',ShieldCheck,'navy'],['fire_station','İtfaiye',Siren,'red']
];

function Home(){
 const nav=useNavigate(); const[q,setQ]=useState('');
 const go=(id:string)=>id==='emergency'?nav('/emergency'):id==='service'?nav('/services'):nav('/nearby',{state:{category:id}});
 const search=(e?:FormEvent)=>{e?.preventDefault();const s=q.toLocaleLowerCase('tr');const hit=Object.entries({eczane:'pharmacy',hastane:'hospital',atm:'atm',akaryakıt:'fuel',market:'market',fırın:'restaurant',taksi:'taxi',polis:'police'}).find(([k])=>s.includes(k));nav('/nearby',{state:{category:hit?.[1]||'pharmacy',query:q}})};
 return <main className="yt-home"><section className="yt-hero"><div className="yt-hero-bg" style={{backgroundImage:`url(${imgs.hero})`}}><div className="yt-hero-overlay"><div><h1>Türkiye'de<br/>İhtiyacın Olan<br/><b>Her Şey Şimdi Yanında.</b></h1><p>Sağlık, güvenlik, ulaşım, günlük ihtiyaçlar ve daha fazlası.<br/>Bul, keşfet, yolunu kolaylaştır.</p></div><form className="yt-hero-search" onSubmit={search}><Search/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Ne arıyorsunuz? (Eczane, ATM, Hastane...)"/><button>Ara</button></form></div><div className="hero-ad"><Ad kind="top"/></div></div></section><section className="quick-grid">{quick.map(([id,label,Icon,c])=><button key={id} onClick={()=>go(id)} className={c}><span><Icon/></span><b>{label}</b></button>)}<button onClick={()=>go('service')} className="more"><span>•••</span><b>Tüm Hizmetler</b></button></section><section className="yt-section"><div className="yt-section-head"><h2>Yakınındaki Popüler Hizmetler</h2><button onClick={()=>go('service')}>Tümünü Gör <ArrowRight/></button></div><div className="popular-grid">{[['Nöbetçi Eczaneler','Şimdi Daha Yakın','pharmacy'],['Hastaneler','En Yakın Hastaneler','hospital'],["ATM'ler",'Tüm Bankalar','market'],['Akaryakıt İstasyonları','En Yakın Benzinciler','fuel'],['Marketler','Zincir Marketler','market'],['Fırınlar','Taze ve Yakın','bakery'],['Ulaşım','Otobüs, Metro, Taksi','transport']].map(([a,b,k])=><button key={a} onClick={()=>go(k)}><img src={imgs[k as keyof typeof imgs]} alt=""/><strong>{a}</strong><small>{b}</small></button>)}</div></section><Ad kind="mid"/><section className="yt-section"><div className="yt-section-head"><h2>Yakınındaki Nöbetçi Eczaneler</h2><button onClick={()=>go('pharmacy')}>Tümünü Gör <ArrowRight/></button></div><div className="pharmacy-grid">{demo.map(p=><MiniPlace key={p.id} p={p}/>)}</div></section><Ad kind="bottom"/></main>
}

function MiniPlace({p}:{p:Place}){return <article className="mini-place"><img src={imgs.pharmacy} alt=""/><div><strong>{p.name}</strong><span><MapPin/> {p.distance} km</span><small>{p.address}</small></div><em>Açık</em><footer><a href={'tel:'+p.phone}><Phone/>Ara</a><a href={'https://www.google.com/maps/dir/?api=1&destination='+p.lat+','+p.lon} target="_blank" rel="noreferrer"><Navigation/>Yol Tarifi</a><button><MapIcon/>Harita</button></footer></article>}

function Nearby(){
 const location=useLocation();const state=(location.state||{}) as {category?:string;province?:string;district?:string};const nav=useNavigate();const[params,setParams]=useSearchParams();
 const[cat,setCat]=useState(params.get('category')||state.category||'pharmacy');const[province,setProvince]=useState(params.get('province')||state.province||'');const[district,setDistrict]=useState(params.get('district')||state.district||'');const[pos,setPos]=useState<Position>();const[places,setPlaces]=useState<Place[]>([]);const[loading,setLoading]=useState(false);const[view,setView]=useState<'list'|'map'>('list');const[err,setErr]=useState('');
 const ds=districtsFor(province);
 useEffect(()=>{const next=new URLSearchParams(params);next.set('category',cat);province?next.set('province',province):next.delete('province');district?next.set('district',district):next.delete('district');setParams(next,{replace:true})},[cat,province,district]);
 useEffect(()=>{if(!pos&&!(province&&district))return;setLoading(true);findPlaces(cat,pos,province,district).then(setPlaces).catch(()=>setPlaces(demo)).finally(()=>setLoading(false))},[cat,pos,province,district]);
 const locate=async()=>{try{setPos(await getCurrentLocation());setProvince('');setDistrict('')}catch(e){setErr(e instanceof LocationError&&e.code==='permission_denied'?'Konum izni verilmedi.':'Konum alınamadı.')}};
 return <main className="inner"><div className="page-title"><button onClick={()=>nav(-1)}>‹</button><div><small>CANLI HİZMET ARAMA</small><h1>Yakınındaki Hizmetler</h1></div><button className="locate" onClick={locate}><LocateFixed/></button></div><div className="filters"><select value={cat} onChange={e=>setCat(e.target.value)}>{categories.filter(c=>!['service','emergency'].includes(c.id)).map(c=><option key={c.id} value={c.id}>{c.label}</option>)}{services.map(s=><option key={s[0]} value={s[0]}>{s[1]}</option>)}</select><select value={province} onChange={e=>{setProvince(e.target.value);setDistrict('');setPos(undefined)}}><option value="">İl seçin</option>{provinces.map(p=><option key={p}>{p}</option>)}</select><select value={district} disabled={!province} onChange={e=>{setDistrict(e.target.value);setPos(undefined)}}><option value="">{province?'İlçe seçin':'Önce il seçin'}</option>{ds.map(d=><option key={d}>{d}</option>)}</select><button onClick={locate}><LocateFixed/></button></div>{err&&<div className="error">{err}</div>}<div className="result-head"><b>Sonuçlar <span>{loading?'…':places.length}</span></b><div><button className={view==='list'?'active':''} onClick={()=>setView('list')}><List/>Liste</button><button className={view==='map'?'active':''} onClick={()=>setView('map')}><MapIcon/>Harita</button></div></div>{view==='map'&&places[0]?<div className="map"><MapContainer center={[places[0].lat,places[0].lon]} zoom={13}><TileLayer attribution="&copy; OpenStreetMap contributors" url="https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png"/>{places.map(p=><Marker key={p.id} position={[p.lat,p.lon]} icon={marker}><Popup><b>{p.name}</b><br/>{p.address}</Popup></Marker>)}</MapContainer></div>:<div className="results">{places.length?places.map(p=><PlaceCard key={p.id} p={p}/>):<div className="empty"><MapPin/><h3>Konumunu kullan veya il / ilçe seç</h3><button onClick={locate}><LocateFixed/>Konumumu Kullan</button></div>}</div>}</main>
}

function PlaceCard({p}:{p:Place}){return <article className="place"><div className="place-icon"><Stethoscope/></div><div className="place-body"><div><h3>{p.name?.trim() || 'İşletme adı bulunamadı'}</h3>{p.isDuty&&<span>NÖBETÇİ</span>}</div><p>{p.address}</p><small><Navigation/> {p.distance?p.distance+' km':'Yakınında'} · <ShieldCheck/> {p.source}</small><footer>{p.phone&&<a href={'tel:'+p.phone}><Phone/>Ara</a>}<a target="_blank" rel="noreferrer" href={'https://www.google.com/maps/dir/?api=1&destination='+p.lat+','+p.lon}><Navigation/>Yol Tarifi</a><button><Heart/>Favori</button></footer></div></article>}

function Services(){const nav=useNavigate();return <main className="inner"><div className="page-title"><button onClick={()=>nav(-1)}>‹</button><div><small>YANINDA TÜRKİYE</small><h1>Çözüm Merkezi</h1></div></div><p className="lead">İhtiyacın olan hizmeti seç, yakındaki işletmeleri bul.</p><div className="services">{services.map(([id,label,Icon])=><button key={id} onClick={()=>nav('/nearby',{state:{category:id}})}><span><Icon/></span><b>{label}</b><ChevronRight/></button>)}</div><button className="business" onClick={()=>nav('/add-business')}><Building2/><div><b>İşletmeni / Hizmetini Ekle</b><small>Ücretsiz başvur · İnceleme sonrası yayın</small></div><ArrowRight/></button></main>}

function Emergency(){return <main className="emergency"><div className="emergency-icon"><Siren/></div><small>ACİL DESTEK</small><h1>Yardıma ihtiyacın<br/><b>varsa Yanında.</b></h1><p>Acil durumda doğru numaraya hızlıca ulaş.</p><div className="emergency-grid">{[['112','Acil Çağrı Merkezi'],['182','Sağlık / MHRS'],['153','Belediye'],['155','Polis']].map(([n,t])=><a key={n} href={'tel:'+n}><strong>{n}</strong><span>{t}</span><Phone/></a>)}</div><a className="call112" href="tel:112"><Phone/>112 Acil Çağrı</a></main>}

function AddBusiness(){const[ok,setOk]=useState(false);const[f,setF]=useState({name:'',category:'',phone:'',whatsapp:'',address:'',province:'İstanbul',district:'Beyoğlu',description:'',hours:''});const ds=districtsFor(f.province);const set=(k:string,v:string)=>setF(x=>({...x,[k]:v}));const submit=async(e:FormEvent)=>{e.preventDefault();const r=await fetch('/api/submissions',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(f)});if(r.ok)setOk(true)};return <main className="form-page"><h1>İşletmeni / Hizmetini Ekle</h1><p>Bilgilerini bırak, inceleme sonrası ücretsiz yayınlayalım.</p>{ok?<div className="success"><ShieldCheck/><h2>Başvurun alındı.</h2></div>:<form onSubmit={submit}><label>İşletme / hizmet adı<input required value={f.name} onChange={e=>set('name',e.target.value)}/></label><label>Kategori<select required value={f.category} onChange={e=>set('category',e.target.value)}><option value="">Seçin</option>{services.map(s=><option key={s[0]} value={s[0]}>{s[1]}</option>)}</select></label><label>Telefon<input required value={f.phone} onChange={e=>set('phone',e.target.value)}/></label><label>WhatsApp<input value={f.whatsapp} onChange={e=>set('whatsapp',e.target.value)}/></label><label>Açık adres<input required value={f.address} onChange={e=>set('address',e.target.value)}/></label><div className="two"><label>İl<select value={f.province} onChange={e=>{set('province',e.target.value);set('district','')}}>{provinces.map(p=><option key={p}>{p}</option>)}</select></label><label>İlçe<select value={f.district} onChange={e=>set('district',e.target.value)}>{ds.map(d=><option key={d}>{d}</option>)}</select></label></div><label>Açıklama<textarea value={f.description} onChange={e=>set('description',e.target.value)}/></label><button>Başvuruyu Gönder <ArrowRight/></button></form>}</main>}

function MenuPage(){return <main className="menu-page"><h1>Menü</h1>{[['/nearby','Yakınımdaki hizmetler',Compass],['/services','Çözüm Merkezi',Wrench],['/emergency','Acil Durum',Siren],['/add-business','İşletmeni Ekle',Building2],['/admin','Admin Girişi',LockKeyhole]].map(([to,t,I])=><NavLink key={String(to)} to={String(to)}><I/><b>{String(t)}</b><ChevronRight/></NavLink>)}</main>}

type AdminStats={visitorsTotal?:number;visitorsToday?:number;searchesTotal?:number};
type AdminAd={id:string|number;title:string;image_url?:string;placement?:string;status?:string};
type AdminData={stats?:AdminStats;ads?:AdminAd[]};
function Admin(){
 const[email,setEmail]=useState(''),[password,setPassword]=useState(''),[ok,setOk]=useState(false),[data,setData]=useState<AdminData>(),[error,setError]=useState('');
 const login=async(e:FormEvent)=>{e.preventDefault();const r=await fetch('/api/admin',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({action:'login',email,password})});if(r.ok){setOk(true)}else setError('Giriş bilgileri hatalı veya admin yapılandırılmamış.')};
 useEffect(()=>{if(ok)fetch('/api/admin').then(r=>r.ok?r.json():null).then(setData).catch(()=>{})},[ok]);
 if(!ok)return <main className="admin-login"><div><ShieldCheck/><h1>Admin Paneli</h1><p>Yanında Türkiye yönetim merkezi</p><form onSubmit={login}><label>E-posta<input type="email" value={email} onChange={e=>setEmail(e.target.value)}/></label><label>Şifre<input type="password" value={password} onChange={e=>setPassword(e.target.value)}/></label>{error&&<div className="error">{error}</div>}<button>Giriş Yap <ArrowRight/></button></form></div></main>;
 const stats=data?.stats||{}; const ads=data?.ads||[];
 return <main className="admin"><aside><div className="admin-brand"><MapPin/> YANINDA <b>TÜRKİYE</b></div>{['Genel Bakış','Hizmetler','Eczaneler','Hastaneler',"ATM'ler",'Akaryakıt','Marketler','Haberler','Reklam Yönetimi','Kullanıcılar','İstatistikler','Ayarlar'].map((x,i)=><button className={i===0?'active':''} key={x}><Activity/>{x}</button>)}</aside><section><header><div><h1>Genel Bakış</h1><p>Yanında Türkiye'nin yönetim merkezi</p></div><div><Bell/> <span>Admin</span><UserCircle/></div></header><div className="stats">{[['Toplam Kullanıcı',stats.visitorsTotal??12548,'↑ 12%'],['Bugünkü Ziyaret',stats.visitorsToday??3245,'↑ 8%'],['Hizmet Aramaları',stats.searchesTotal??8420,'↑ 15%'],['Reklam Geliri','₺1.250','↑ 20%']].map(([a,b,c])=><article key={String(a)}><small>{a}</small><strong>{b}</strong><span>{c}</span></article>)}</div><div className="admin-grid"><div className="panel"><h2>Son 7 Gün Ziyaretçi Grafiği</h2><div className="chart">{[35,50,47,65,48,76,90].map((h,i)=><i key={i} style={{height:h+'%'}}/>)}</div></div><div className="panel"><h2>En Çok Kullanılan Hizmetler</h2>{[['Nöbetçi Eczane',32],['Hastane',18],['ATM',12],['Akaryakıt',10],['Market',8]].map(([x,n])=><div className="bar" key={String(x)}><span>{x}</span><i style={{width:Number(n)*2.2+'%'}}/><b>{n}%</b></div>)}</div></div><div className="panel ads"><div className="panel-title"><div><h2>Reklam Yönetimi</h2><p>Web sitesindeki reklam alanlarını yönet</p></div><button>+ Yeni Reklam Ekle</button></div>{(ads.length?ads:[{id:1,title:'Ana Banner',image_url:imgs.hero,placement:'1200×600'},{id:2,title:'Orta Banner',image_url:imgs.burger,placement:'1200×200'},{id:3,title:'Alt Banner',image_url:imgs.trend,placement:'1200×200'}]).map((ad:AdminAd)=><div className="ad-row" key={ad.id}><img src={ad.image_url||imgs.hero} alt=""/><div><b>{ad.title}</b><small>{ad.placement}</small></div><span>Aktif</span><button>Düzenle</button></div>)}</div></section></main>
}

function Simple({title}:{title:string}){return <main className="simple"><h1>{title}</h1><p>Yanında Türkiye.</p></main>}

export default function TargetApp(){
 return <div><Header/><Routes><Route path="/" element={<Home/>}/><Route path="/nearby" element={<Nearby/>}/><Route path="/services" element={<Services/>}/><Route path="/emergency" element={<Emergency/>}/><Route path="/add-business" element={<AddBusiness/>}/><Route path="/menu" element={<MenuPage/>}/><Route path="/admin" element={<Admin/>}/><Route path="/favorites" element={<Simple title="Favoriler"/>}/><Route path="/news" element={<Simple title="Haberler"/>}/><Route path="/contact" element={<Simple title="İletişim"/>}/><Route path="*" element={<Home/>}/></Routes><MobileNav/></div>
}